#!/usr/bin/env node
var analyze = require('commonform-analyze')
var fs = require('fs')

var ID = process.argv[2]
var EDITION = process.argv[3]

var commonform = JSON.parse(fs.readFileSync('build/' + ID + '.json'))
var signatures = JSON.parse(fs.readFileSync(ID + '.signatures'))
var description = fs.readFileSync(ID + '.description', 'utf8').trim()
console.log(JSON.stringify({
  title: ID,
  edition: EDITION,
  published: new Date().toISOString(),
  notes: [description],
  repository: 'https://github.com/rxnda/' + ID,
  commonform: commonform,
  directions: directionsFor(commonform),
  signatures: signatures
}))

function directionsFor (commonform) {
  var returned = analyze(commonform)
    .blanks
    .map(function (keyarray) {
      return {blank: keyarray}
    })

  returned[0].label = 'Purpose'
  returned[0].notes = [
    'Describe the reason the parties will ' +
    'share confidential information.'
  ]
  returned[0].examples = [
    'discussing the purchase of business software'
  ]

  return returned
}
